version: '3'
services:
  web:
    image: nextcloud:23.0.12-apache
    ports:
      - "8080:80"
    volumes:
      - ./nextcloud:/var/www/html/data
    user: "1000:0"
    # user: "1000:1000"
    environment:
      - SQLITE_DATABASE ="owncloud.db"
      - NEXTCLOUD_ADMIN_USER="admin"
      - NEXTCLOUD_ADMIN_PASSWORD="admin"
